language: php

branches:
  # Only test the main branch and SemVer tags.
  only:
    - main
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: 'SCENARIO=symfony4 DEPENDENCIES="update"'
    - php: 7.3
    - php: 7.2
    - php: 7.1
      env: 'SCENARIO=symfony4'

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - '.scenarios.lock/install "${SCENARIO}" "${DEPENDENCIES-install}"'

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls -v
